config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :users, except: [:new]
  resources :articles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'signup', to: 'users#new'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true, length: { minimum: 3, maximum: 20 }
    validates_uniqueness_of :name

    has_many :article_categories
    has_many :articles, through: :article_categories
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :require_admin, except: [:index, :show]
    before_action :set_category, only: [:edit, :update, :show]

    def index
        @categories = Category.paginate(page: params[:page], per_page: 3)
    end

    def new
        @category = Category.new
    end

    def create
        @category = Category.new(category_params)
        if @category.save
            flash[:success] = 'Category created successfully'
            redirect_to categories_path
        else
            render 'new'
        end
    end

    def edit
    end

    def update
        if @category.update(category_params)
            flash[:success] = "Category updated"
            redirect_to category_path(@category)
        else
            render 'edit'
        end
    end

    def show
        @category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
    end

    private

    def require_admin
        if !logged_in? || (logged_in? and !current_user.admin?)
            flash[:danger] = 'User not allowed to perform the action.'
            redirect_to categories_path
        end
    end

    def category_params
        params.require(:category).permit(:name)
    end

    def set_category
        @category = Category.find(params[:id])
    end
end

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %> &nbsp;</span>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>

<%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    <div class="form-group">
        <div class="control-label col-sm-2">
            <%= f.label :name %>
        </div>
        <div class="col-sm-8">
            <%= f.text_field :name, class:"form-control", placeholder:"Enter category name", autofocus: true %>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <%= f.submit class: "btn btn-primary btn-lg" %>
        </div>
    </div>
<%end%>
<div class='col-xs-4 col-xs-offset-4'>
    [ <%= link_to 'Cancel', articles_path %> ]
</div>

app/views/categories/edit.html.erb
<h1 align='center'>Edit category name</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1 align='center'>All Categories</h1>

<div align='center'>
    <%= will_paginate %>
    <% @categories.each do |category| %>
        <ul class='listing'>
            <div class='row'>
                <div class='well col-md-4 col-md-offset-4'>
                    <li class='article-title'>
                        <%= link_to "#{category.name}", category_path(category) %>
                    </li>
                    <li>
                        <small><%= pluralize(category.articles.count, 'article') %></small>
                    </li>
                </div>
            </div>
        </ul>
    <%end%>
    <%= will_paginate %>
</div>

app/views/categories/new.html.erb
<h1 align='center'>Create new category</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<h1 align="center"><%= "Category: " + @category.name %></h1>
<div align="center">
    <% if logged_in? and current_user.admin? %>
        <div class='row'>
            <span class='badge'><%= link_to "Edit category name", edit_category_path(@category) %></span>
        </div>
    <% end %>
    <%= will_paginate @category_articles %>
</div>
<%= render 'articles/article', obj: @category_articles %>
<div align="center">
    <%= will_paginate @category_articles %>
</div>